[build]
  base = "."
  publish = "dist"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/.netlify/functions"

# 클라이언트 사이드 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 서버리스 함수 설정
[functions]
  directory = "netlify/functions"
  
# 함수 별칭 설정 - 수정된 함수를 사용하도록 리다이렉션
[[redirects]]
  from = "/.netlify/functions/analyze"
  to = "/.netlify/functions/analyze-fixed"
  status = 200

[[redirects]]
  from = "/.netlify/functions/analysis/*"
  to = "/.netlify/functions/analysis-fixed/:splat"
  status = 200
