[build]
  base = "."
  publish = "dist"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)README.md' ':(exclude)*.md' ':(exclude)package-lock.json'"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions"

# CSS 파일 MIME 타입 설정
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# 아이콘 및 이미지 캐싱 최적화
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30일

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30일

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30일

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # 1년
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/og-simple.svg"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400"
    Content-Type = "image/png"

[[headers]]
  for = "/twitter-image.png"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400"
    Content-Type = "image/png"

[[headers]]
  for = "/kakao-image.png"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400"
    Content-Type = "image/png"

[[headers]]
  for = "/icon-simple.svg"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

# 정적 파일 캐싱 및 MIME 타입 설정
[[headers]]
  for = "/src/styles/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' data: https://fonts.gstatic.com https://cdn.jsdelivr.net;"

# 정적 리소스에 대한 리다이렉트 제외 규칙 (CSS 파일이 HTML로 리다이렉트되는 것 방지)
[[redirects]]
  from = "/src/styles/*"
  to = "/src/styles/:splat"
  status = 200

# Client-side routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP to HTTPS 리다이렉트
[[redirects]]
  from = "http://destiny33.site/*"
  to = "https://destiny33.site/:splat"
  status = 301
  force = true

# www to non-www 리다이렉트
[[redirects]]
  from = "https://www.destiny33.site/*"
  to = "https://destiny33.site/:splat"
  status = 301
  force = true

# Netlify 도메인에서 커스텀 도메인으로 리다이렉트
[[redirects]]
  from = "https://destiny33.netlify.app/*"
  to = "https://destiny33.site/:splat"
  status = 301
  force = true

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serverless functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
