[build]
  base = "."
  publish = "dist"
  command = "npm run build:client && npm run build:functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/.netlify/functions"

# Force HTTPS - 모든 HTTP 요청을 HTTPS로 리다이렉션
[[redirects]]
  from = "http://www.destiny33.site/*"
  to = "https://www.destiny33.site/:splat"
  status = 301
  force = true

# Redirect non-www to www (SEO best practice)
[[redirects]]
  from = "https://destiny33.site/*"
  to = "https://www.destiny33.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://destiny33.site/*"
  to = "https://www.destiny33.site/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' data: https://fonts.gstatic.com https://cdn.jsdelivr.net;"

# Client-side routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serverless functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
