[build]
  base = "."
  publish = "dist"
  command = "npm run build:client && npm run build:functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "/.netlify/functions"

# CSS 파일 MIME 타입 설정
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# 정적 파일 캐싱 및 MIME 타입 설정
[[headers]]
  for = "/src/styles/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' data: https://fonts.gstatic.com https://cdn.jsdelivr.net;"

# 정적 리소스에 대한 리다이렉트 제외 규칙 (CSS 파일이 HTML로 리다이렉트되는 것 방지)
[[redirects]]
  from = "/src/styles/*"
  to = "/src/styles/:splat"
  status = 200

# Client-side routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serverless functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
